<?php

/**
 * @file
 * AskViv Misc module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function askviv_misc_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // UI tweaks for preset filters on listing pages.
  if (in_array($form_id, ['node_listing_page_form', 'node_listing_page_edit_form'])) {

    // The help text is not relevant. Unset it.
    unset($form['field_listing']['widget'][0]['arguments']['#description']);
    unset($form['field_listing']['widget'][0]['arguments']['#title']);
    $form['field_listing']['widget'][0]['arguments']['#attributes'] = [
      'class' => ['hidden']
    ];

    unset($form['field_listing']['widget'][0]['token_help']);
  }
}
